### ISSUE TITLE
Dynamic DNS as IP

### ISSUE THREAD

**Issue by Krishna-Noutiyal** [antonioCoco/ConPtyShell#8]
I tried using it with Dynamic DNS instead of IP Address but there is an error :

`
ConPtyShellException: [-] ConPtyShellException:
ConPtyShell: Invalid remoteIp valuedevildenny.ddns.net
   at ConPtyShellMainClass.CheckRemoteIpArg(String ipString)
   at ConPtyShellMainClass.ConPtyShellMain(String[] args)
`

**Comment by antonioCoco** [comment]
hostname is not supported currently.

Anyway good idea, i will add support for hostname usage in a future release.

**Comment by Omar-D** [comment]
alert("Ahmed");
